[package]
name = "breez-sdk-liquid-cli"
edition = "2021"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
bip39 = "2.0.0"
breez-sdk-liquid = { path = "../lib" }
clap = { version = "4.5.1", features = ["derive"] }
env_logger = "0.11"
log = "0.4.20"
rustyline = { version = "13.0.0", features = ["derive"] }
