targets:
  $default:
    sources:
      exclude:
        # Exclude symlinks for iOS, Linux & Windows builds
        - example/ios/.symlinks/**
        - example/linux/flutter/ephemeral/.plugin_symlinks/**
        - example/windows/flutter/ephemeral/.plugin_symlinks/**